/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package utp.edu.pe.nexoket.jform;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import org.bson.Document;

import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;

import utp.edu.pe.nexoket.db.MongoDBConnection;

/**
 *
 * @author User
 */
public class ItmClientes extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloTabla;
    private MongoCollection<Document> coleccionClientes;
    private String codigoClienteEnEdicion = null;
    private boolean modoEdicion = false;

    /**
     * Creates new form MenuPrincipal
     */
    public ItmClientes() {
        initComponents();
        this.coleccionClientes = MongoDBConnection.getInstance().getDatabase().getCollection("Cliente");
        configurarTabla();
        configurarListeners();
        cargarClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFiltro = new javax.swing.JTextField();
        btnBuscarFiltro = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        btnLimpiarCampos = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Clientes");
        setToolTipText("");

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblClientes);

        jLabel1.setText("Nombre");

        jLabel2.setText("Correo");

        jLabel3.setText("Contraseña");

        jLabel4.setText("Filtro");

        btnBuscarFiltro.setText("Buscar");

        btnEditar.setText("Editar");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");

        jLabel5.setText("DNI");

        jLabel6.setText("Telefono");

        jLabel7.setText("Apellido");

        jLabel8.setText("Direccion");

        btnLimpiarCampos.setText("Limpiar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6))
                                .addGap(38, 38, 38))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(34, 34, 34)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFiltro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscarFiltro)
                                .addGap(42, 42, 42)
                                .addComponent(btnEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiarCampos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar)
                                .addGap(13, 13, 13))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .addComponent(txtTelefono))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(txtContraseña))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnBuscarFiltro)
                    .addComponent(btnEditar)
                    .addComponent(btnAgregar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiarCampos))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * Configura la tabla con las columnas apropiadas
     */
    private void configurarTabla() {
        String[] columnas = {"Código", "Nombres", "Apellidos", "DNI", "Teléfono", "Correo", "Contraseña", "Dirección", "Activo"};
        modeloTabla = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Hacer la tabla no editable
            }
        };
        tblClientes.setModel(modeloTabla);
    }

    /**
     * Configura los listeners de los botones y tabla
     */
    private void configurarListeners() {
        // Listener para seleccionar fila de la tabla
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int filaSeleccionada = tblClientes.getSelectedRow();
                if (filaSeleccionada != -1) {
                    cargarClienteEnFormulario(filaSeleccionada);
                }
            }
        });

        // Listeners de botones
        btnAgregar.addActionListener(e -> agregarCliente());
        btnEditar.addActionListener(e -> actualizarCliente());
        btnEliminar.addActionListener(e -> eliminarCliente());
        btnBuscarFiltro.addActionListener(e -> filtrarClientes());
    }

    /**
     * Carga todos los clientes desde MongoDB
     */
    private void cargarClientes() {
        modeloTabla.setRowCount(0);
        
        try (MongoCursor<Document> cursor = coleccionClientes.find().iterator()) {
            while (cursor.hasNext()) {
                Document doc = cursor.next();
                Object[] fila = {
                    doc.getString("codigoCliente"),
                    doc.getString("nombres"),
                    doc.getString("apellidos"),
                    doc.getString("dni"),
                    doc.getString("telefono"),
                    doc.getString("correo"),
                    doc.getString("contraseña"),
                    doc.getString("direccion"),
                    doc.getBoolean("activo") ? "Sí" : "No"
                };
                modeloTabla.addRow(fila);
            }
            
            System.out.println("✓ " + modeloTabla.getRowCount() + " clientes cargados");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error al cargar clientes: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    /**
     * Carga un cliente seleccionado en el formulario
     */
    private void cargarClienteEnFormulario(int fila) {
        codigoClienteEnEdicion = modeloTabla.getValueAt(fila, 0).toString();
        txtNombre.setText(modeloTabla.getValueAt(fila, 1).toString());
        txtApellido.setText(modeloTabla.getValueAt(fila, 2).toString());
        txtDNI.setText(modeloTabla.getValueAt(fila, 3).toString());
        txtTelefono.setText(modeloTabla.getValueAt(fila, 4).toString());
        txtCorreo.setText(modeloTabla.getValueAt(fila, 5).toString());
        txtContraseña.setText(modeloTabla.getValueAt(fila, 6).toString());
        txtDireccion.setText(modeloTabla.getValueAt(fila, 7).toString());
        
        modoEdicion = true;
        btnAgregar.setEnabled(false);
        btnEditar.setEnabled(true);
    }

    /**
     * Agregar nuevo cliente
     */
    private void agregarCliente() {
        // Validar campos
        if (txtNombre.getText().trim().isEmpty() || txtApellido.getText().trim().isEmpty() || 
            txtDNI.getText().trim().isEmpty() || txtCorreo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Por favor, complete los campos obligatorios:\nNombre, Apellido, DNI y Correo",
                "Campos incompletos",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // Generar código de cliente automático
            String codigoCliente = generarCodigoCliente();
            
            Document nuevoCliente = new Document()
                .append("codigoCliente", codigoCliente)
                .append("nombres", txtNombre.getText().trim())
                .append("apellidos", txtApellido.getText().trim())
                .append("dni", txtDNI.getText().trim())
                .append("telefono", txtTelefono.getText().trim())
                .append("correo", txtCorreo.getText().trim())
                .append("contraseña", txtContraseña.getText().trim())
                .append("direccion", txtDireccion.getText().trim())
                .append("fechaRegistro", new java.util.Date())
                .append("activo", true);

            coleccionClientes.insertOne(nuevoCliente);

            JOptionPane.showMessageDialog(this,
                "✅ Cliente registrado exitosamente\n" +
                "Código: " + codigoCliente,
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE);

            limpiarFormulario();
            cargarClientes();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error al registrar cliente: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    /**
     * Actualizar cliente existente
     */
    private void actualizarCliente() {
        if (codigoClienteEnEdicion == null) {
            JOptionPane.showMessageDialog(this,
                "Seleccione un cliente de la tabla para editar",
                "Validación",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            Document filtro = new Document("codigoCliente", codigoClienteEnEdicion);
            Document actualizacion = new Document("$set", new Document()
                .append("nombres", txtNombre.getText().trim())
                .append("apellidos", txtApellido.getText().trim())
                .append("dni", txtDNI.getText().trim())
                .append("telefono", txtTelefono.getText().trim())
                .append("correo", txtCorreo.getText().trim())
                .append("contraseña", txtContraseña.getText().trim())
                .append("direccion", txtDireccion.getText().trim()));

            coleccionClientes.updateOne(filtro, actualizacion);

            JOptionPane.showMessageDialog(this,
                "✅ Cliente actualizado exitosamente",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE);

            limpiarFormulario();
            cargarClientes();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error al actualizar cliente: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    /**
     * Eliminar cliente
     */
    private void eliminarCliente() {
        int filaSeleccionada = tblClientes.getSelectedRow();
        
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this,
                "Seleccione un cliente de la tabla para eliminar",
                "Validación",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        String codigoCliente = modeloTabla.getValueAt(filaSeleccionada, 0).toString();
        String nombreCliente = modeloTabla.getValueAt(filaSeleccionada, 1).toString();

        int confirmacion = JOptionPane.showConfirmDialog(this,
            "¿Está seguro de eliminar el cliente?\n\n" +
            "Código: " + codigoCliente + "\n" +
            "Nombre: " + nombreCliente,
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);

        if (confirmacion == JOptionPane.YES_OPTION) {
            try {
                Document filtro = new Document("codigoCliente", codigoCliente);
                coleccionClientes.deleteOne(filtro);

                JOptionPane.showMessageDialog(this,
                    "✅ Cliente eliminado exitosamente",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE);

                limpiarFormulario();
                cargarClientes();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                    "Error al eliminar cliente: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }

    /**
     * Filtrar clientes por búsqueda
     */
    private void filtrarClientes() {
        String filtro = txtFiltro.getText().trim().toLowerCase();
        
        if (filtro.isEmpty()) {
            cargarClientes();
            return;
        }

        modeloTabla.setRowCount(0);

        try (MongoCursor<Document> cursor = coleccionClientes.find().iterator()) {
            int contador = 0;
            
            while (cursor.hasNext()) {
                Document doc = cursor.next();
                
                String codigo = doc.getString("codigoCliente").toLowerCase();
                String nombres = doc.getString("nombres").toLowerCase();
                String apellidos = doc.getString("apellidos").toLowerCase();
                String dni = doc.getString("dni").toLowerCase();
                String correo = doc.getString("correo").toLowerCase();
                
                if (codigo.contains(filtro) || nombres.contains(filtro) || 
                    apellidos.contains(filtro) || dni.contains(filtro) || correo.contains(filtro)) {
                    
                    Object[] fila = {
                        doc.getString("codigoCliente"),
                        doc.getString("nombres"),
                        doc.getString("apellidos"),
                        doc.getString("dni"),
                        doc.getString("telefono"),
                        doc.getString("correo"),
                        doc.getString("contraseña"),
                        doc.getString("direccion"),
                        doc.getBoolean("activo") ? "Sí" : "No"
                    };
                    modeloTabla.addRow(fila);
                    contador++;
                }
            }
            
            System.out.println("✓ " + contador + " clientes encontrados con filtro: " + filtro);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error al filtrar clientes: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    /**
     * Generar código de cliente automático
     */
    private String generarCodigoCliente() {
        try {
            long count = coleccionClientes.countDocuments();
            return String.format("CLI%03d", count + 1);
        } catch (Exception e) {
            return "CLI001";
        }
    }

    /**
     * Limpiar formulario
     */
    private void limpiarFormulario() {
        txtNombre.setText("");
        txtApellido.setText("");
        txtDNI.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
        txtContraseña.setText("");
        txtDireccion.setText("");
        txtFiltro.setText("");
        
        codigoClienteEnEdicion = null;
        modoEdicion = false;
        btnAgregar.setEnabled(true);
        btnEditar.setEnabled(true);
        
        tblClientes.clearSelection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscarFiltro;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiarCampos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFiltro;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
