/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package utp.edu.pe.nexoket.jform;

import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import utp.edu.pe.nexoket.facade.ProductoFacade;
import utp.edu.pe.nexoket.modelo.Producto;

/**
 *
 * @author User
 */
public class ItmProductos extends javax.swing.JInternalFrame {

    private final ProductoFacade productoFacade;
    private DefaultTableModel modeloTabla;
    private boolean modoEdicion = false; // Indica si estamos en modo edición
    private String codigoProductoEnEdicion = null; // Código del producto que se está editando

    /**
     * Creates new form ItmProductos
     */
    public ItmProductos() {
        initComponents();
        this.productoFacade = new ProductoFacade();
        configurarTabla();
        cargarDatosTabla();
        configurarListeners();
        // Generar código inicial basado en la categoría seleccionada por defecto
        try {
            generarCodigoAutomatico();
        } catch (Exception e) {
            System.out.println("Error al generar código inicial: " + e.getMessage());
            // Código por defecto si hay error
            txtCodigo.setText("ABA001");
        }
    }
    
    /**
     * Configura los listeners necesarios
     */
    private void configurarListeners() {
        // Listener para selección de filas en la tabla
        tblProductos.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && tblProductos.getSelectedRow() >= 0) {
                // La fila está seleccionada, el usuario puede hacer clic en Actualizar
                // No cargamos automáticamente, esperamos el clic en el botón
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        txtNombre = new javax.swing.JLabel();
        txtMarca = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbIGV = new javax.swing.JComboBox<>();
        cmbCategoria = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnEscanear = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtRegistroEscaner = new javax.swing.JTextField();

        setClosable(true);
        setResizable(true);
        setTitle("Registrar Producto");

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblProductos);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        txtNombre.setText("Nombre:");

        txtMarca.setText("Marca:");

        jLabel3.setText("Categoria:");

        jLabel4.setText("Descripcion:");

        jLabel1.setText("Unidad/Medida:");

        jLabel2.setText("Precio de Compra:");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel5.setText("Precio de Venta:");

        jLabel6.setText("Aplicar IGV:");

        cmbIGV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Habilitado", "Deshabilitado" }));

        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Abarrotes", "Bebidas", "Snacks" }));

        jLabel7.setText("Stock:");

        jLabel8.setText("Limte de Stock:");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel9.setText("Ubicacion:");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel10.setText("Estado:");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });

        lblCodigo.setText("Codigo:");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnEscanear.setText("Escaner");

        jLabel11.setText("R-Codigo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre)
                            .addComponent(txtMarca)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField5)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2)
                    .addComponent(jTextField4)
                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField6)
                    .addComponent(jTextField7)
                    .addComponent(cmbIGV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField8)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(lblCodigo)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(jTextField3)
                            .addComponent(cmbEstado, 0, 104, Short.MAX_VALUE)
                            .addComponent(btnEscanear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(txtRegistroEscaner))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 972, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMarca)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(cmbIGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodigo)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimpiar)
                        .addGap(8, 8, 8)
                        .addComponent(btnAgregar)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminar)
                            .addComponent(btnEscanear)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnActualizar)
                            .addComponent(txtRegistroEscaner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminarProducto();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void cmbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {
        // Generar código automáticamente basado en la categoría seleccionada
        generarCodigoAutomatico();
    }

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {
        actualizarProducto();
    }
    
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {
        agregarProducto();
    }
    
    /**
     * Actualiza un producto existente en la base de datos
     * Primera pulsación: Carga datos del producto seleccionado en los campos
     * Segunda pulsación: Guarda los cambios si hubo modificaciones, o limpia campos si no hubo cambios
     */
    private void actualizarProducto() {
        try {
            // Verificar que haya un producto seleccionado en la tabla
            int filaSeleccionada = tblProductos.getSelectedRow();
            if (filaSeleccionada < 0) {
                JOptionPane.showMessageDialog(this, 
                    "Por favor, seleccione un producto de la tabla", 
                    "Validación", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            // Obtener el código del producto seleccionado
            String codigoSeleccionado = (String) modeloTabla.getValueAt(filaSeleccionada, 0);
            
            // PRIMERA PULSACIÓN: Cargar datos para editar
            if (!modoEdicion) {
                Producto producto = productoFacade.buscarProducto(codigoSeleccionado);
                
                if (producto != null) {
                    // Cargar datos en los campos
                    txtCodigo.setText(producto.getCodigo());
                    jTextField1.setText(producto.getNombre());
                    jTextField2.setText(producto.getMarca() != null ? producto.getMarca() : "");
                    jTextField3.setText(producto.getUbicacion() != null ? producto.getUbicacion() : "");
                    jTextField4.setText(producto.getDescripcion() != null ? producto.getDescripcion() : "");
                    jTextField5.setText(producto.getUnidadMedida() != null ? producto.getUnidadMedida() : "");
                    jTextField6.setText(""); // Precio compra no disponible en modelo simple
                    jTextField7.setText(String.valueOf(producto.getPrecio()));
                    jTextField8.setText(String.valueOf(producto.getStock()));
                    jTextField9.setText(String.valueOf(producto.getStockMinimo()));
                    
                    // Seleccionar categoría
                    String categoria = producto.getCategoria();
                    if (categoria != null) {
                        cmbCategoria.setSelectedItem(categoria);
                    }
                    
                    // Seleccionar estado
                    cmbEstado.setSelectedItem(producto.isActivo() ? "Activo" : "Inactivo");
                    
                    // Activar modo edición
                    modoEdicion = true;
                    codigoProductoEnEdicion = codigoSeleccionado;
                    
                    // Cambiar texto del botón
                    btnActualizar.setText("Guardar Cambios");
                    
                    JOptionPane.showMessageDialog(this, 
                        "Producto cargado. Realice los cambios y presione 'Guardar Cambios'.", 
                        "Modo edición", 
                        JOptionPane.INFORMATION_MESSAGE);
                }
                return;
            }
            
            // SEGUNDA PULSACIÓN: Verificar si hay cambios y guardar
            if (modoEdicion && codigoProductoEnEdicion != null) {
                // Obtener producto original
                Producto productoOriginal = productoFacade.buscarProducto(codigoProductoEnEdicion);
                
                if (productoOriginal == null) {
                    JOptionPane.showMessageDialog(this, 
                        "Error: No se pudo encontrar el producto original", 
                        "Error", 
                        JOptionPane.ERROR_MESSAGE);
                    resetearModoEdicion();
                    return;
                }
                
                // Verificar si hubo cambios
                boolean huboChangios = detectarCambios(productoOriginal);
                
                if (!huboChangios) {
                    // No hubo cambios, solo limpiar campos
                    JOptionPane.showMessageDialog(this, 
                        "No se detectaron cambios. Limpiando campos...", 
                        "Sin cambios", 
                        JOptionPane.INFORMATION_MESSAGE);
                    limpiarCampos();
                    resetearModoEdicion();
                    return;
                }
                
                // Validar campos antes de guardar
                if (jTextField1.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, 
                        "El nombre es obligatorio", 
                        "Validación", 
                        JOptionPane.WARNING_MESSAGE);
                    return;
                }
                
                // Validar precio de venta
                double precioVenta;
                try {
                    precioVenta = Double.parseDouble(jTextField7.getText().trim());
                    if (precioVenta <= 0) {
                        JOptionPane.showMessageDialog(this, 
                            "El precio de venta debe ser mayor a 0", 
                            "Validación", 
                            JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, 
                        "El precio de venta debe ser un número válido", 
                        "Validación", 
                        JOptionPane.WARNING_MESSAGE);
                    return;
                }
                
                // Validar stock
                int stock;
                try {
                    stock = Integer.parseInt(jTextField8.getText().trim());
                    if (stock < 0) {
                        JOptionPane.showMessageDialog(this, 
                            "El stock no puede ser negativo", 
                            "Validación", 
                            JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, 
                        "El stock debe ser un número entero válido", 
                        "Validación", 
                        JOptionPane.WARNING_MESSAGE);
                    return;
                }
                
                // Obtener datos de los campos
                String codigo = txtCodigo.getText().trim();
                String nombre = jTextField1.getText().trim();
                String marca = jTextField2.getText().trim();
                String categoria = (String) cmbCategoria.getSelectedItem();
                String descripcion = jTextField4.getText().trim();
                String unidadMedida = jTextField5.getText().trim();
                
                // Stock mínimo
                int stockMinimo = 5;
                try {
                    String stockMinimoStr = jTextField9.getText().trim();
                    if (!stockMinimoStr.isEmpty()) {
                        stockMinimo = Integer.parseInt(stockMinimoStr);
                    }
                } catch (NumberFormatException e) {
                    stockMinimo = 5;
                }
                
                String ubicacion = jTextField3.getText().trim();
                
                // Confirmar actualización
                int confirmacion = JOptionPane.showConfirmDialog(this, 
                    "¿Está seguro de actualizar el producto " + codigo + "?", 
                    "Confirmar actualización", 
                    JOptionPane.YES_NO_OPTION);
                
                if (confirmacion != JOptionPane.YES_OPTION) {
                    return;
                }
                
                // Llamar al facade para actualizar el producto
                boolean exito = productoFacade.actualizarProducto(
                    codigo, nombre, marca, categoria,
                    "", // subcategoría
                    unidadMedida,
                    1, // cantidadPorUnidad
                    descripcion,
                    precioVenta,
                    stock,
                    stockMinimo,
                    "", // proveedor
                    null, // fechaVencimiento
                    ubicacion
                );
                
                if (exito) {
                    JOptionPane.showMessageDialog(this, 
                        "Producto actualizado exitosamente.\nFecha de actualización registrada.", 
                        "Éxito", 
                        JOptionPane.INFORMATION_MESSAGE);
                    
                    // Limpiar campos y resetear modo
                    limpiarCampos();
                    resetearModoEdicion();
                    
                    // Refrescar tabla
                    cargarDatosTabla();
                } else {
                    JOptionPane.showMessageDialog(this, 
                        "Error al actualizar el producto", 
                        "Error", 
                        JOptionPane.ERROR_MESSAGE);
                }
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error inesperado: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            resetearModoEdicion();
        }
    }
    
    /**
     * Detecta si hubo cambios entre el producto original y los campos actuales
     */
    private boolean detectarCambios(Producto productoOriginal) {
        try {
            // Comparar cada campo
            if (!productoOriginal.getNombre().equals(jTextField1.getText().trim())) {
                return true;
            }
            
            String marcaOriginal = productoOriginal.getMarca() != null ? productoOriginal.getMarca() : "";
            if (!marcaOriginal.equals(jTextField2.getText().trim())) {
                return true;
            }
            
            String ubicacionOriginal = productoOriginal.getUbicacion() != null ? productoOriginal.getUbicacion() : "";
            if (!ubicacionOriginal.equals(jTextField3.getText().trim())) {
                return true;
            }
            
            String descripcionOriginal = productoOriginal.getDescripcion() != null ? productoOriginal.getDescripcion() : "";
            if (!descripcionOriginal.equals(jTextField4.getText().trim())) {
                return true;
            }
            
            String unidadMedidaOriginal = productoOriginal.getUnidadMedida() != null ? productoOriginal.getUnidadMedida() : "";
            if (!unidadMedidaOriginal.equals(jTextField5.getText().trim())) {
                return true;
            }
            
            double precioVenta = Double.parseDouble(jTextField7.getText().trim());
            if (Math.abs(productoOriginal.getPrecio() - precioVenta) > 0.01) {
                return true;
            }
            
            int stock = Integer.parseInt(jTextField8.getText().trim());
            if (productoOriginal.getStock() != stock) {
                return true;
            }
            
            int stockMinimo = Integer.parseInt(jTextField9.getText().trim());
            if (productoOriginal.getStockMinimo() != stockMinimo) {
                return true;
            }
            
            String categoriaOriginal = productoOriginal.getCategoria() != null ? productoOriginal.getCategoria() : "";
            String categoriaActual = (String) cmbCategoria.getSelectedItem();
            if (!categoriaOriginal.equals(categoriaActual)) {
                return true;
            }
            
            boolean estadoOriginal = productoOriginal.isActivo();
            boolean estadoActual = cmbEstado.getSelectedItem().equals("Activo");
            if (estadoOriginal != estadoActual) {
                return true;
            }
            
            return false; // No hubo cambios
            
        } catch (Exception e) {
            // Si hay error al comparar, asumimos que hubo cambios
            return true;
        }
    }
    
    /**
     * Resetea el modo edición
     */
    private void resetearModoEdicion() {
        modoEdicion = false;
        codigoProductoEnEdicion = null;
        btnActualizar.setText("Actualizar");
    }
    
    /**
     * Agrega un nuevo producto a la base de datos
     */
    private void agregarProducto() {
        try {
            // Validar que los campos obligatorios estén llenos
            if (txtCodigo.getText().trim().isEmpty() || 
                jTextField1.getText().trim().isEmpty() ||
                jTextField7.getText().trim().isEmpty() ||
                jTextField8.getText().trim().isEmpty()) {
                
                JOptionPane.showMessageDialog(this, 
                    "Por favor, rellene todos los campos obligatorios:\n" +
                    "- Código\n" +
                    "- Nombre\n" +
                    "- Precio de Venta\n" +
                    "- Stock", 
                    "Rellenar Campos", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            // Validar precio de venta
            double precioVenta = 0;
            try {
                precioVenta = Double.parseDouble(jTextField7.getText().trim());
                if (precioVenta <= 0) {
                    JOptionPane.showMessageDialog(this, 
                        "El precio de venta debe ser mayor a 0", 
                        "Validación", 
                        JOptionPane.WARNING_MESSAGE);
                    jTextField7.requestFocus();
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, 
                    "El precio de venta debe ser un número válido", 
                    "Validación", 
                    JOptionPane.WARNING_MESSAGE);
                jTextField7.requestFocus();
                return;
            }
            
            // Validar stock
            int stock = 0;
            try {
                stock = Integer.parseInt(jTextField8.getText().trim());
                if (stock < 0) {
                    JOptionPane.showMessageDialog(this, 
                        "El stock no puede ser negativo", 
                        "Validación", 
                        JOptionPane.WARNING_MESSAGE);
                    jTextField8.requestFocus();
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, 
                    "El stock debe ser un número entero válido", 
                    "Validación", 
                    JOptionPane.WARNING_MESSAGE);
                jTextField8.requestFocus();
                return;
            }
            
            // Obtener datos de los campos
            String codigo = txtCodigo.getText().trim();
            String nombre = jTextField1.getText().trim();
            String marca = jTextField2.getText().trim();
            String categoria = (String) cmbCategoria.getSelectedItem();
            String descripcion = jTextField4.getText().trim();
            String unidadMedida = jTextField5.getText().trim();
            
            // Precio de compra (opcional)
            double precioCompra = 0;
            try {
                String precioCompraStr = jTextField6.getText().trim();
                if (!precioCompraStr.isEmpty()) {
                    precioCompra = Double.parseDouble(precioCompraStr);
                }
            } catch (NumberFormatException e) {
                precioCompra = 0;
            }
            
            // Stock mínimo (opcional)
            int stockMinimo = 0;
            try {
                String stockMinimoStr = jTextField9.getText().trim();
                if (!stockMinimoStr.isEmpty()) {
                    stockMinimo = Integer.parseInt(stockMinimoStr);
                }
            } catch (NumberFormatException e) {
                stockMinimo = 5; // Valor por defecto
            }
            
            String ubicacion = jTextField3.getText().trim();
            
            // Llamar al facade para registrar el producto
            boolean exito = productoFacade.registrarProducto(
                codigo, nombre, marca, categoria,
                "", // subcategoría (vacía por ahora)
                unidadMedida,
                1, // cantidadPorUnidad por defecto
                descripcion,
                precioVenta,
                stock,
                stockMinimo,
                "", // proveedor (vacío por ahora)
                null, // fechaVencimiento
                ubicacion
            );
            
            if (exito) {
                JOptionPane.showMessageDialog(this, 
                    "Producto agregado exitosamente", 
                    "Éxito", 
                    JOptionPane.INFORMATION_MESSAGE);
                
                // Limpiar campos
                limpiarCampos();
                
                // Refrescar tabla
                cargarDatosTabla();
                
                // Generar nuevo código
                generarCodigoAutomatico();
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Error al agregar el producto. El código ya existe o hay datos inválidos.", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error inesperado: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    
    /**
     * Limpia todos los campos del formulario
     */
    private void limpiarCampos() {
        jTextField1.setText(""); // Nombre
        jTextField2.setText(""); // Marca
        jTextField3.setText(""); // Ubicación
        jTextField4.setText(""); // Descripción
        jTextField5.setText(""); // Unidad/Medida
        jTextField6.setText(""); // Precio Compra
        jTextField7.setText(""); // Precio Venta
        jTextField8.setText(""); // Stock
        jTextField9.setText(""); // Stock Mínimo
        cmbCategoria.setSelectedIndex(0);
        cmbEstado.setSelectedIndex(0);
        cmbIGV.setSelectedIndex(0);
        tblProductos.clearSelection();
        generarCodigoAutomatico();
        jTextField1.requestFocus(); // Poner el foco en el campo nombre
        resetearModoEdicion(); // Resetear el modo edición
    }
    
    /**
     * Carga los datos del producto seleccionado en los campos
     */
    private void cargarDatosProductoEnCampos() {
        int filaSeleccionada = tblProductos.getSelectedRow();
        if (filaSeleccionada >= 0) {
            String codigo = (String) modeloTabla.getValueAt(filaSeleccionada, 0);
            Producto producto = productoFacade.buscarProducto(codigo);
            
            if (producto != null) {
                txtCodigo.setText(producto.getCodigo());
                jTextField1.setText(producto.getNombre());
                jTextField2.setText(producto.getMarca() != null ? producto.getMarca() : "");
                jTextField3.setText(producto.getUbicacion() != null ? producto.getUbicacion() : "");
                jTextField4.setText(producto.getDescripcion() != null ? producto.getDescripcion() : "");
                jTextField5.setText(producto.getUnidadMedida() != null ? producto.getUnidadMedida() : "");
                jTextField6.setText(""); // Precio compra no disponible en modelo simple
                jTextField7.setText(String.valueOf(producto.getPrecio()));
                jTextField8.setText(String.valueOf(producto.getStock()));
                jTextField9.setText(String.valueOf(producto.getStockMinimo()));
                
                // Seleccionar categoría
                String categoria = producto.getCategoria();
                if (categoria != null) {
                    cmbCategoria.setSelectedItem(categoria);
                }
                
                // Seleccionar estado
                cmbEstado.setSelectedItem(producto.isActivo() ? "Activo" : "Inactivo");
            }
        }
    }
    
    /**
     * Elimina un producto de la base de datos (eliminación lógica)
     */
    private void eliminarProducto() {
        try {
            // Verificar que haya un producto seleccionado en la tabla
            int filaSeleccionada = tblProductos.getSelectedRow();
            if (filaSeleccionada < 0) {
                JOptionPane.showMessageDialog(this, 
                    "Por favor, seleccione un producto de la tabla para eliminar", 
                    "Validación", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            // Obtener el código del producto seleccionado
            String codigo = (String) modeloTabla.getValueAt(filaSeleccionada, 0);
            String nombre = (String) modeloTabla.getValueAt(filaSeleccionada, 1);
            
            // Confirmar eliminación
            int confirmacion = JOptionPane.showConfirmDialog(this, 
                "¿Está seguro de eliminar el producto?\n\n" +
                "Código: " + codigo + "\n" +
                "Nombre: " + nombre + "\n\n" +
                "Esta acción marcará el producto como inactivo.", 
                "Confirmar eliminación", 
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
            
            if (confirmacion != JOptionPane.YES_OPTION) {
                return;
            }
            
            // Llamar al facade para eliminar el producto (eliminación lógica)
            boolean exito = productoFacade.eliminarProducto(codigo);
            
            if (exito) {
                JOptionPane.showMessageDialog(this, 
                    "Producto eliminado exitosamente.\n" +
                    "El producto " + codigo + " ha sido marcado como inactivo.", 
                    "Éxito", 
                    JOptionPane.INFORMATION_MESSAGE);
                
                // Limpiar campos
                limpiarCampos();
                
                // Refrescar tabla
                cargarDatosTabla();
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Error al eliminar el producto", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error inesperado: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    
    /**
     * Prueba rápida de conectividad con MongoDB
     */
    private void probarConectividadRapida() {
        try {
            System.out.println("=== PRUEBA DE CONECTIVIDAD ===");
            
            // Probar obtener todos los productos con información detallada
            List<Producto> productos = productoFacade.obtenerTodosLosProductos();
            System.out.println("Productos obtenidos del facade: " + productos.size());
            
            // Mostrar información en consola
            for (Producto p : productos) {
                System.out.println("Producto encontrado: " + p.getCodigo() + " - " + p.getNombre());
            }
            
        } catch (Exception e) {
            System.out.println("Error en prueba de conectividad: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    /**
     * Método de prueba para verificar la conexión y datos
     */
    private void probarConexionDB() {
        try {
            // Probar conexión y obtener datos
            List<Producto> todosLosProductos = productoFacade.obtenerTodosLosProductos();
            List<Producto> productosActivos = productoFacade.obtenerProductosActivos();
            
            StringBuilder mensaje = new StringBuilder();
            mensaje.append("=== DIAGNÓSTICO DE BASE DE DATOS ===\n");
            mensaje.append("Total de productos en BD: ").append(todosLosProductos.size()).append("\n");
            mensaje.append("Productos activos: ").append(productosActivos.size()).append("\n\n");
            
            if (!todosLosProductos.isEmpty()) {
                mensaje.append("=== PRIMEROS 3 PRODUCTOS ===\n");
                for (int i = 0; i < Math.min(3, todosLosProductos.size()); i++) {
                    Producto p = todosLosProductos.get(i);
                    mensaje.append("- Código: ").append(p.getCodigo())
                           .append(", Nombre: ").append(p.getNombre())
                           .append(", Activo: ").append(p.isActivo()).append("\n");
                }
            } else {
                mensaje.append("¡No se encontraron productos en la base de datos!\n");
                mensaje.append("Verifique:\n");
                mensaje.append("1. Conexión a MongoDB\n");
                mensaje.append("2. Nombre de la base de datos\n");
                mensaje.append("3. Nombre de la colección (Producto vs Productos)\n");
            }
            
            JOptionPane.showMessageDialog(this, 
                mensaje.toString(), 
                "Diagnóstico de BD", 
                JOptionPane.INFORMATION_MESSAGE);
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error en diagnóstico: " + e.getMessage(), 
                "Error de Conexión", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    /**
     * Configura el modelo de la tabla con las columnas necesarias
     */
    private void configurarTabla() {
        // Definir columnas de la tabla
        String[] columnas = {"Código", "Nombre", "Marca", "Categoría", "Stock", "Precio", "Estado", "Ubicación"};
        
        // Crear modelo de tabla no editable
        modeloTabla = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Hacer que la tabla no sea editable
            }
        };
        
        // Asignar el modelo a la tabla
        tblProductos.setModel(modeloTabla);
        
        // Configurar ancho de columnas
        tblProductos.getColumnModel().getColumn(0).setPreferredWidth(80);  // Código
        tblProductos.getColumnModel().getColumn(1).setPreferredWidth(200); // Nombre
        tblProductos.getColumnModel().getColumn(2).setPreferredWidth(120); // Marca
        tblProductos.getColumnModel().getColumn(3).setPreferredWidth(120); // Categoría
        tblProductos.getColumnModel().getColumn(4).setPreferredWidth(80);  // Stock
        tblProductos.getColumnModel().getColumn(5).setPreferredWidth(100); // Precio
        tblProductos.getColumnModel().getColumn(6).setPreferredWidth(80);  // Estado
        tblProductos.getColumnModel().getColumn(7).setPreferredWidth(120); // Ubicación
        
        // Habilitar selección de filas
        tblProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    }
    
    /**
     * Carga los datos de productos desde la base de datos a la tabla
     */
    private void cargarDatosTabla() {
        try {
            // Limpiar tabla
            modeloTabla.setRowCount(0);
            
            // Primero intentar obtener todos los productos
            List<Producto> productos = productoFacade.obtenerTodosLosProductos();
            System.out.println("DEBUG: Número total de productos obtenidos: " + productos.size());
            
            // Si no hay productos, mostrar mensaje
            if (productos.isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                    "No se encontraron productos en la colección 'Productos'.\n" +
                    "Verifique la conexión a MongoDB.", 
                    "Sin datos", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            // Llenar la tabla con los datos
            for (Producto producto : productos) {
                System.out.println("DEBUG: Procesando producto: " + producto.getCodigo() + " - " + producto.getNombre());
                
                Object[] fila = new Object[8];
                fila[0] = producto.getCodigo() != null ? producto.getCodigo() : "Sin código";
                fila[1] = producto.getNombre() != null ? producto.getNombre() : "Sin nombre";
                fila[2] = producto.getMarca() != null ? producto.getMarca() : "Sin marca";
                fila[3] = producto.getCategoria() != null ? producto.getCategoria() : "Sin categoría";
                fila[4] = producto.getStock();
                fila[5] = String.format("S/. %.2f", producto.getPrecio());
                fila[6] = producto.isActivo() ? "Activo" : "Inactivo";
                fila[7] = producto.getUbicacion() != null ? producto.getUbicacion() : "Sin ubicación";
                
                modeloTabla.addRow(fila);
            }
            
            System.out.println("DEBUG: Tabla cargada exitosamente con " + modeloTabla.getRowCount() + " filas");
            
            // Mostrar mensaje de éxito
            JOptionPane.showMessageDialog(this, 
                "Productos cargados exitosamente: " + productos.size() + " productos encontrados", 
                "Carga exitosa", 
                JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception e) {
            String errorMsg = "Error al cargar los productos: " + e.getMessage();
            System.out.println("DEBUG ERROR: " + errorMsg);
            
            JOptionPane.showMessageDialog(this, 
                errorMsg, 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    
    /**
     * Refresca los datos de la tabla
     */
    public void refrescarTabla() {
        cargarDatosTabla();
    }
    
    /**
     * Obtiene el producto seleccionado en la tabla
     */
    public Producto obtenerProductoSeleccionado() {
        int filaSeleccionada = tblProductos.getSelectedRow();
        if (filaSeleccionada >= 0) {
            String codigo = (String) modeloTabla.getValueAt(filaSeleccionada, 0);
            return productoFacade.buscarProducto(codigo);
        }
        return null;
    }
    
    /**
     * Genera un código automático basado en la categoría seleccionada
     */
    private void generarCodigoAutomatico() {
        try {
            String categoriaSeleccionada = (String) cmbCategoria.getSelectedItem();
            if (categoriaSeleccionada != null && !categoriaSeleccionada.isEmpty()) {
                String codigoGenerado = productoFacade.generarCodigoPorCategoria(categoriaSeleccionada);
                txtCodigo.setText(codigoGenerado);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error al generar código: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEscanear;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbIGV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JLabel txtMarca;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JTextField txtRegistroEscaner;
    // End of variables declaration//GEN-END:variables
}
