/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package utp.edu.pe.nexoket.jform;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.List;

import javax.swing.BorderFactory;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.Timer;

import com.google.zxing.BarcodeFormat;

import utp.edu.pe.nexoket.facade.ProductoFacade;
import utp.edu.pe.nexoket.modelo.Producto;
import utp.edu.pe.nexoket.util.WebcamBarcodeScanner;

/**
 * Formulario para registrar stock usando escáner de webcam
 * @author User
 */
public class ItmRegistrarStock extends javax.swing.JInternalFrame {

    private final ProductoFacade productoFacade;
    private WebcamBarcodeScanner scanner;
    private Producto productoActual;
    private boolean camaraActiva = false;
    private JPanel panelCamara; // Panel para mostrar la cámara

    /**
     * Creates new form ItmRegistrarStock
     */
    public ItmRegistrarStock() {
        initComponents();
        this.productoFacade = new ProductoFacade();
        configurarComponentes();
        cargarProductosEnCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbProductosDB = new javax.swing.JComboBox<>();
        btnEscanearCodigoProducto = new javax.swing.JButton();
        txtCodigoEscaneado = new javax.swing.JTextField();
        txtCantidadRegistrado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registrar Stock");

        btnEscanearCodigoProducto.setText("Escanear");

        jLabel1.setText("Seleccionar Producto:");

        jLabel2.setText("Codigo Escaneado");

        jLabel3.setText("Stock Actual");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbProductosDB, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnEscanearCodigoProducto))
                    .addComponent(jLabel1))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodigoEscaneado, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtCantidadRegistrado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbProductosDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEscanearCodigoProducto)
                    .addComponent(txtCodigoEscaneado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadRegistrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Configura los componentes del formulario
     */
    private void configurarComponentes() {
        // Configurar campo de cantidad (mostrará el stock actual)
        txtCantidadRegistrado.setEditable(false);
        txtCantidadRegistrado.setText("0");

        // Configurar botón de escanear
        btnEscanearCodigoProducto.setText("📷 Activar Cámara");
        btnEscanearCodigoProducto.addActionListener(e -> toggleCamera());
        
        // Configurar listener del combo box
        cmbProductosDB.addActionListener(e -> cmbProductosDBActionPerformed(null));
        
        // Deshabilitar campo de texto al inicio
        txtCodigoEscaneado.setEditable(false);
        txtCodigoEscaneado.setText("Presione 'Activar Cámara' para comenzar");
        
        // Crear panel para la cámara
        panelCamara = new JPanel();
        panelCamara.setLayout(new BorderLayout());
        panelCamara.setPreferredSize(new Dimension(640, 480));
        panelCamara.setBorder(BorderFactory.createTitledBorder("Vista de Cámara"));
        panelCamara.setVisible(false); // Oculto por defecto
        
        // Agregar panel de cámara al formulario
        getContentPane().add(panelCamara, BorderLayout.NORTH);
    }
    
    /**
     * Carga productos en el combo box
     */
    private void cargarProductosEnCombo() {
        try {
            cmbProductosDB.removeAllItems();
            cmbProductosDB.addItem("-- Seleccione o escanee un producto --");
            
            List<Producto> productos = productoFacade.obtenerProductosActivos();
            
            for (Producto p : productos) {
                cmbProductosDB.addItem(p.getCodigo() + " - " + p.getNombre());
            }
            
            System.out.println("✓ " + productos.size() + " productos cargados");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error al cargar productos: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Activa o desactiva la cámara
     */
    private void toggleCamera() {
        if (!camaraActiva) {
            activarCamara();
        } else {
            desactivarCamara();
        }
    }
    
    /**
     * Activa la cámara y el escáner
     */
    private void activarCamara() {
        try {
            System.out.println("===========================================");
            System.out.println("🎥 INICIANDO CÁMARA...");
            System.out.println("===========================================");
            
            // Verificar si hay webcam disponible
            if (!WebcamBarcodeScanner.hasWebcam()) {
                System.out.println("❌ ERROR: No se detectó ninguna webcam");
                JOptionPane.showMessageDialog(this,
                    "❌ No se detectó ninguna webcam\n\n" +
                    "Asegúrese de que la cámara esté conectada y\n" +
                    "no esté siendo usada por otra aplicación.",
                    "Webcam no encontrada",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            System.out.println("✅ Webcam detectada correctamente");
            
            // Crear el escáner
            scanner = new WebcamBarcodeScanner();
            System.out.println("✅ Escáner creado exitosamente");
            
            // Limpiar panel y agregar el escáner
            panelCamara.removeAll();
            panelCamara.add(scanner, BorderLayout.CENTER);
            panelCamara.setVisible(true);
            
            System.out.println("✅ Vista de cámara agregada al panel");
            
            // Iniciar el escaneo con callback (asegurar ejecución en EDT para operaciones Swing)
            scanner.startScanner((code, format) -> {
                javax.swing.SwingUtilities.invokeLater(() -> procesarCodigoEscaneado(code, format));
            });
            
            System.out.println("✅ Escáner iniciado - Esperando códigos de barras...");
            
            camaraActiva = true;
            btnEscanearCodigoProducto.setText("🛑 Detener Cámara");
            txtCodigoEscaneado.setText("Escaneando... coloque código frente a cámara");
            
            // Redimensionar ventana
            revalidate();
            repaint();
            
            System.out.println("✅ CÁMARA ACTIVA Y FUNCIONANDO");
            System.out.println("📷 Coloque el código de barras frente a la cámara");
            System.out.println("===========================================");
            
            mostrarNotificacionTemporal("✅ Cámara activada exitosamente", Color.GREEN);
            
        } catch (Exception e) {
            System.out.println("❌ ERROR al activar la cámara: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "Error al activar la cámara:\n" + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Desactiva la cámara
     */
    private void desactivarCamara() {
        System.out.println("🛑 DETENIENDO CÁMARA...");
        
        if (scanner != null) {
            scanner.stopScanner();
            scanner = null;
            System.out.println("✅ Escáner detenido");
        }
        
        panelCamara.removeAll();
        panelCamara.setVisible(false);
        
        camaraActiva = false;
        btnEscanearCodigoProducto.setText("📷 Activar Cámara");
        txtCodigoEscaneado.setText("Cámara desactivada");
        
        revalidate();
        repaint();
        
        System.out.println("✅ Cámara desactivada correctamente");
        System.out.println("===========================================");
    }
    
    /**
     * Procesa el código escaneado por la cámara
     * El código escaneado es secundario y se registra para el producto principal seleccionado
     */
    private void procesarCodigoEscaneado(String codigo, BarcodeFormat format) {
        try {
            System.out.println("\n📷 CÓDIGO SECUNDARIO DETECTADO");
            System.out.println("-------------------------------------------");
            
            // Validar que hay un producto principal seleccionado
            if (productoActual == null) {
                System.out.println("⚠️ No hay producto principal seleccionado");
                System.out.println("-------------------------------------------");
                
                java.awt.Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this,
                    "⚠️ SELECCIONE UN PRODUCTO PRINCIPAL\n\n" +
                    "Por favor, seleccione primero el producto principal\n" +
                    "desde el combo box antes de escanear códigos.",
                    "Producto no seleccionado",
                    JOptionPane.WARNING_MESSAGE);
                
                if (scanner != null) scanner.resetLastCode();
                return;
            }
            
            if (codigo == null) codigo = "";
            codigo = codigo.trim();
            
            System.out.println("Código escaneado (secundario): " + codigo);
            System.out.println("Formato: " + format.name());
            System.out.println("Producto principal: " + productoActual.getCodigo() + " - " + productoActual.getNombre());
            
            txtCodigoEscaneado.setText(codigo + " [" + format.name() + "]");

            // Comprobación simple: códigos demasiado cortos probablemente no sean válidos
            if (codigo.length() < 3) {
                System.out.println("⚠️ Código demasiado corto (longitud: " + codigo.length() + ")");
                System.out.println("-------------------------------------------");
                
                if (scanner != null) scanner.resetLastCode();
                JOptionPane.showMessageDialog(this,
                    "No se detectó un código válido. Asegúrese de apuntar al código de barras (no solo a los números) y de tener buena iluminación.",
                    "Código inválido",
                    JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            System.out.println("✅ Código válido detectado");
            
            // Sonido de éxito
            java.awt.Toolkit.getDefaultToolkit().beep();
            
            // Registrar automáticamente +1 al producto principal (sin confirmación)
            System.out.println("📦 Registrando +1 para: " + productoActual.getNombre());
            System.out.println("-------------------------------------------");
            
            registrarStock();
            
        } catch (Exception e) {
            System.out.println("❌ ERROR: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "Error al procesar código: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Carga el producto en el formulario
     */
    private void cargarProductoEnFormulario(Producto producto) {
        // Buscar y seleccionar en combo
        String buscar = producto.getCodigo() + " - " + producto.getNombre();
        
        for (int i = 0; i < cmbProductosDB.getItemCount(); i++) {
            String item = cmbProductosDB.getItemAt(i);
            if (item.startsWith(producto.getCodigo())) {
                cmbProductosDB.setSelectedIndex(i);
                break;
            }
        }
        
        // Mostrar stock actual en el campo de cantidad
        txtCantidadRegistrado.setText(String.valueOf(producto.getStock()));
    }
    
    /**
     * Listener para el combo box
     */
    private void cmbProductosDBActionPerformed(java.awt.event.ActionEvent evt) {
        String seleccion = (String) cmbProductosDB.getSelectedItem();
        
        if (seleccion != null && !seleccion.startsWith("--")) {
            String codigo = seleccion.split(" - ")[0];
            productoActual = productoFacade.buscarProducto(codigo);
            
            // Mostrar stock actual del producto seleccionado
            if (productoActual != null) {
                txtCantidadRegistrado.setText(String.valueOf(productoActual.getStock()));
                System.out.println("\n📦 PRODUCTO PRINCIPAL SELECCIONADO:");
                System.out.println("   Código: " + productoActual.getCodigo());
                System.out.println("   Nombre: " + productoActual.getNombre());
                System.out.println("   Stock actual: " + productoActual.getStock());
                System.out.println("-------------------------------------------");
            }
        } else {
            productoActual = null;
            txtCantidadRegistrado.setText("0");
        }
    }
    
    /**
     * Registra el stock automáticamente (sin confirmación)
     */
    private void registrarStock() {
        try {
            if (productoActual == null) {
                System.out.println("⚠️ No hay producto seleccionado");
                return;
            }

            // Incremento automático por escaneo: +1
            int cantidad = 1;

            int stockAnterior = productoActual.getStock();
            int nuevoStock = stockAnterior + cantidad;

            // Actualizar en BD (sin confirmación)
            System.out.println("💾 REGISTRANDO EN BASE DE DATOS...");
            
            boolean exito = productoFacade.aumentarStock(productoActual.getCodigo(), cantidad);

            if (exito) {
                System.out.println("✅ REGISTRO EXITOSO:");
                System.out.println("   Producto: " + productoActual.getNombre());
                System.out.println("   Código: " + productoActual.getCodigo());
                System.out.println("   Stock anterior: " + stockAnterior);
                System.out.println("   Cantidad agregada: +" + cantidad);
                System.out.println("   Stock nuevo: " + nuevoStock);
                System.out.println("-------------------------------------------\n");
                
                // Actualizar el objeto productoActual con el nuevo stock
                productoActual.setStock(nuevoStock);
                
                // Reflejar nuevo stock en formulario EN TIEMPO REAL
                txtCantidadRegistrado.setText(String.valueOf(nuevoStock));
                
                // Sonido de éxito
                java.awt.Toolkit.getDefaultToolkit().beep();

                // Mostrar notificación temporal (sin bloquear)
                mostrarNotificacionTemporal("✅ +1 Stock: " + productoActual.getNombre() + " (Total: " + nuevoStock + ")", Color.GREEN);

                // Resetear escáner para siguiente código
                if (scanner != null) {
                    scanner.resetLastCode();
                }

            } else {
                System.out.println("❌ ERROR: No se pudo actualizar el stock en la base de datos");
                System.out.println("-------------------------------------------");
                
                java.awt.Toolkit.getDefaultToolkit().beep();
                java.awt.Toolkit.getDefaultToolkit().beep();
                
                mostrarNotificacionTemporal("❌ Error al registrar", Color.RED);
                
                if (scanner != null) {
                    scanner.resetLastCode();
                }
            }

        } catch (Exception e) {
            System.out.println("❌ EXCEPCIÓN: " + e.getMessage());
            e.printStackTrace();
            
            java.awt.Toolkit.getDefaultToolkit().beep();
            mostrarNotificacionTemporal("❌ Error: " + e.getMessage(), Color.RED);
            
            if (scanner != null) {
                scanner.resetLastCode();
            }
        }
    }
    
    /**
     * Limpia el formulario
     */
    private void limpiarFormulario() {
        productoActual = null;
        txtCantidadRegistrado.setText("0");
        cmbProductosDB.setSelectedIndex(0);
        txtCodigoEscaneado.setText("Listo para escanear siguiente código");
    }
    
    /**
     * Muestra una notificación temporal que desaparece automáticamente
     */
    private void mostrarNotificacionTemporal(String mensaje, Color color) {
        // Crear diálogo sin decoración
        JDialog notificacion = new JDialog();
        notificacion.setUndecorated(true);
        notificacion.setAlwaysOnTop(true);
        
        // Crear panel con el mensaje
        JPanel panel = new JPanel();
        panel.setBackground(color);
        panel.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2));
        
        JLabel label = new JLabel(mensaje);
        label.setFont(new Font("Arial", Font.BOLD, 16));
        label.setForeground(Color.WHITE);
        label.setHorizontalAlignment(SwingConstants.CENTER);
        
        panel.add(label);
        notificacion.add(panel);
        notificacion.pack();
        
        // Centrar en la pantalla
        notificacion.setLocationRelativeTo(this);
        
        // Hacer visible
        notificacion.setVisible(true);
        
        // Timer para cerrar automáticamente después de 2 segundos
        Timer timer = new Timer(2000, e -> {
            notificacion.dispose();
        });
        timer.setRepeats(false);
        timer.start();
        
        System.out.println("📢 NOTIFICACIÓN MOSTRADA: " + mensaje);
    }
    
    /**
     * Al cerrar, detener la cámara
     */
    @Override
    public void dispose() {
        desactivarCamara();
        super.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEscanearCodigoProducto;
    private javax.swing.JComboBox<String> cmbProductosDB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtCantidadRegistrado;
    private javax.swing.JTextField txtCodigoEscaneado;
    // End of variables declaration//GEN-END:variables
}
