package utp.edu.pe.nexoket.jform;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import utp.edu.pe.nexoket.jform.ItmProductos;

/**
 *
 * @author User
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form NewApplication
     */
    
    public MenuPrincipal() {
        
        initComponents();
        this.setContentPane(this.escritorio);
        
        // Maximizar ventana a pantalla completa
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon("src/main/java/imagenes/banner.jpeg");
        Image image = icon.getImage();
        escritorio = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        }
        ;
        menuBar = new javax.swing.JMenuBar();
        MenuRegistro = new javax.swing.JMenu();
        MnItemClientes = new javax.swing.JMenuItem();
        MnItemProveedores = new javax.swing.JMenuItem();
        MnItmRegistrarStock = new javax.swing.JMenuItem();
        MenuVentas = new javax.swing.JMenu();
        MnItemRegistrarVenta = new javax.swing.JMenuItem();
        MnItemHistorialVentas = new javax.swing.JMenuItem();
        MenuCompras = new javax.swing.JMenu();
        MnItemAgregarProductos = new javax.swing.JMenuItem();
        MenuInventario = new javax.swing.JMenu();
        MnItemProductos = new javax.swing.JMenuItem();
        MenuReportes = new javax.swing.JMenu();
        MnItemConsulta = new javax.swing.JMenuItem();
        MenuCerrarSesion = new javax.swing.JMenu();
        MnItemCerrarSesion = new javax.swing.JMenuItem();
        MnItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1223, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        menuBar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        MenuRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        MenuRegistro.setMnemonic('f');
        MenuRegistro.setText("Registros");
        MenuRegistro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MenuRegistro.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                MenuRegistroAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        MnItemClientes.setText("Clientes");
        MnItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItemClientesActionPerformed(evt);
            }
        });
        MenuRegistro.add(MnItemClientes);

        MnItemProveedores.setText("Proveedores");
        MnItemProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItemProveedoresActionPerformed(evt);
            }
        });
        MenuRegistro.add(MnItemProveedores);

        MnItmRegistrarStock.setText("Stock");
        MnItmRegistrarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItmRegistrarStockActionPerformed(evt);
            }
        });
        MenuRegistro.add(MnItmRegistrarStock);

        menuBar.add(MenuRegistro);

        MenuVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/factura.png"))); // NOI18N
        MenuVentas.setMnemonic('e');
        MenuVentas.setText("Ventas");
        MenuVentas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        MnItemRegistrarVenta.setText("Registrar Venta");
        MnItemRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItemRegistrarVentaActionPerformed(evt);
            }
        });
        MenuVentas.add(MnItemRegistrarVenta);

        MnItemHistorialVentas.setText("Historial de Ventas");
        MnItemHistorialVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItemHistorialVentasActionPerformed(evt);
            }
        });
        MenuVentas.add(MnItemHistorialVentas);

        menuBar.add(MenuVentas);

        MenuCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/letter.png"))); // NOI18N
        MenuCompras.setText("Compras");
        MenuCompras.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        MnItemAgregarProductos.setText("Agregar Productos");
        MenuCompras.add(MnItemAgregarProductos);

        menuBar.add(MenuCompras);

        MenuInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/reportes1.png"))); // NOI18N
        MenuInventario.setMnemonic('h');
        MenuInventario.setText("Inventario");
        MenuInventario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        MnItemProductos.setText("Productos");
        MnItemProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItemProductosActionPerformed(evt);
            }
        });
        MenuInventario.add(MnItemProductos);

        menuBar.add(MenuInventario);

        MenuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/historial1.png"))); // NOI18N
        MenuReportes.setText("Reportes");
        MenuReportes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        MnItemConsulta.setText("Agente de Consulta");
        MenuReportes.add(MnItemConsulta);

        menuBar.add(MenuReportes);

        MenuCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/log-out.png"))); // NOI18N
        MenuCerrarSesion.setText("Cerrar Sesion");
        MenuCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        MnItemCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cerrarsesion.png"))); // NOI18N
        MnItemCerrarSesion.setText("Cerrar Sesion");
        MenuCerrarSesion.add(MnItemCerrarSesion);

        MnItemSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cross.png"))); // NOI18N
        MnItemSalir.setText("Salir");
        MnItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItemSalirActionPerformed(evt);
            }
        });
        MenuCerrarSesion.add(MnItemSalir);

        menuBar.add(MenuCerrarSesion);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MnItemSalirActionPerformed

    private void MenuRegistroAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_MenuRegistroAncestorAdded
        // Este método se ejecuta cuando se agrega el ancestro, no es necesario aquí
    }//GEN-LAST:event_MenuRegistroAncestorAdded
    
    private void MnItemProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItemProductosActionPerformed
        ItmProductos productosForm = new ItmProductos();
        productosForm.setVisible(true);
        escritorio.add(productosForm);
        
    }//GEN-LAST:event_MnItemProductosActionPerformed

    private void MnItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItemClientesActionPerformed
        ItmClientes clientesForm = new ItmClientes();
        clientesForm.setVisible(true);
        escritorio.add(clientesForm);
    }//GEN-LAST:event_MnItemClientesActionPerformed

    private void MnItemProveedoresActionPerformed(java.awt.event.ActionEvent evt) {
        ItmProovedores proveedoresForm = new ItmProovedores();
        proveedoresForm.setVisible(true);
        escritorio.add(proveedoresForm);
    }
    
    private void MnItmRegistrarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItmRegistrarStockActionPerformed
        ItmRegistrarStock registrarStockForm = new ItmRegistrarStock();
        registrarStockForm.setVisible(true);
        escritorio.add(registrarStockForm);
    }//GEN-LAST:event_MnItmRegistrarStockActionPerformed

    private void MnItemRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItemRegistrarVentaActionPerformed
        // TODO add your handling code here:
        ItmRegistrarVenta registrarVentaForm = new ItmRegistrarVenta();
        registrarVentaForm.setVisible(true);
        escritorio.add(registrarVentaForm);
    }//GEN-LAST:event_MnItemRegistrarVentaActionPerformed

    private void MnItemHistorialVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItemHistorialVentasActionPerformed
        ItmHistorialVentas historialForm = new ItmHistorialVentas();
        historialForm.setVisible(true);
        escritorio.add(historialForm);
    }//GEN-LAST:event_MnItemHistorialVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuCerrarSesion;
    private javax.swing.JMenu MenuCompras;
    private javax.swing.JMenu MenuInventario;
    private javax.swing.JMenu MenuRegistro;
    private javax.swing.JMenu MenuReportes;
    private javax.swing.JMenu MenuVentas;
    private javax.swing.JMenuItem MnItemAgregarProductos;
    private javax.swing.JMenuItem MnItemCerrarSesion;
    private javax.swing.JMenuItem MnItemClientes;
    private javax.swing.JMenuItem MnItemConsulta;
    private javax.swing.JMenuItem MnItemProductos;
    private javax.swing.JMenuItem MnItemProveedores;
    private javax.swing.JMenuItem MnItemRegistrarVenta;
    private javax.swing.JMenuItem MnItemHistorialVentas;
    private javax.swing.JMenuItem MnItemSalir;
    private javax.swing.JMenuItem MnItmRegistrarStock;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
